---
- name: Create a VIP, pool and pool members
  hosts: f5lb
  connection: local
  vars:
    provider:
      password: August1!0
      server: 192.168.1.12
      user: root
      validate_certs: no
      server_port: 443
  tasks:
    - name: Create a pool
      bigip_pool:
        provider: "{{ provider }}"
        lb_method: ratio-member
        name: web143-test1
        slow_ramp_time: 120
      delegate_to: localhost
    - name: Add members to pool
      bigip_pool_member:
        provider: "{{ provider }}"
        description: webserver {{ item.name }}
        host: "{{ item.host }}"
        name: "{{ item.name }}"
        pool: web143-test1
        port: 80
      with_items:
        - host: 10.10.10.50
          name: web01-143
        - host: 10.10.10.51
          name: web02-143
      delegate_to: localhost
    - name: Create a VIP
      bigip_virtual_server:
        provider: "{{ provider }}"
        description: foo-vip-143
        destination: 172.16.10.118
        name: foo-vip-143
        pool: web143
        port: 80
        snat: Automap
        profiles:
          - http
          - clientssl
      delegate_to: localhost